- name: Ensure Python MySQL client is installed (for Python 3)
  ansible.builtin.apt:
    name:
      - python3-pymysql
      - python3-mysqldb
    state: present
  become: true

- name: Ensure the database exists
  community.mysql.mysql_db:
    login_host: database-1.c3qw2oqme9gi.ap-south-1.rds.amazonaws.com
    login_user: admin
    login_password: passRDS02
    name: database-1
    state: present


- name: Create users table if it does not exist
  community.mysql.mysql_query:
    login_host: database-1.c3qw2oqme9gi.ap-south-1.rds.amazonaws.com
    login_user: admin
    login_password: passRDS02
    login_db: database-1
    query: |
          CREATE TABLE IF NOT EXISTS users (
            id INT PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            profile_picture_url VARCHAR(255) DEFAULT NULL
          );
