---
- name: Create .env file
  copy:
    dest: /home/ubuntu/Profile-App/.env
    content: |
      DB_HOST=
      DB_USER=
      DB_PASSWORD=
      DB_NAME=
      S3_BUCKET=
      AWS_ACCESS_KEY_ID=
      AWS_SECRET_ACCESS_KEY=
      AWS_REGION=
    mode: '0600'
    owner: ubuntu
    group: ubuntu

